### PR TITLE
team 3 submits a pull request to team 1's test branch

### PR DESCRIPTION
**Pull request by atsoroka**

### CODE REVIEW

**Comment by cocochrane** [comment]
@atsoroka and team: Thanks for making this pull request! I have a few questions and requests for changes-let me know if you have any questions!

1. Can you save the timeseries (in generateTS.py) as a timeseries using pickle?
2. What is going on with the interpolating times? The times should be a part of the timeseries when stored so interpolation shouldn’t be necessary (this may be because you stored them not as timeseries)?
3. Can you give the user the option for how many similar timeseries to find? I.e. python genSimilarity.py tsdata/ts398.dat —n 5 would give you the 5 closest, etc.
4. Instead of only printing the resulting similar filename, can you save these files to a "Results" folder in pickle format?
5. Did you have any test files?
6. Can you write a short Readme to clearly explain in which order files should be called in, and how, if they have any arguments?

**Comment by atsoroka** [comment]
Thanks will do.  BTW, I'm unfamiliar with this Git emailing/communication.
Do give me a shout if I am not responding in the right format.

**Comment by atsoroka** [comment]
Hi Courtney, thanks again for your feedback.  Regarding your requests:

2.What is going on with the interpolating times? The times should be a part of the timeseries when stored so interpolation shouldn’t be necessary (this may be because you stored them not as timeseries)?

Amended.  Now we are only interpolating for genSimilarity passed timeseries, where we need to insure same sampling rate as tsmaker generated timeseries.

4.Instead of only printing the resulting similar filename, can you save these files to a "Results" folder

Added

5. Did you have any test files?

Added

6. Can you write a short Readme to clearly explain in which order files should be called in, and how, if they have any arguments?

Added

Regarding Pickle Request, and "get N Closest", as discussed in lab today, these requests are not required from our team.  We should however be able to get to that shortly.

Thanks and please let me know if you have any other feedback.

**Comment by cocochrane** [comment]
Thank you for making those changes! No worries if you can't get to those last items. I'll now merge and do a final check!

**Pull request closed without merging**
